# -*- coding: utf-8 -*-
"""tidy.py — what is in files/, what needs it, and what nothing needs.

READ-ONLY. This script deletes nothing and writes nothing. It prints an inventory
and a set of findings, and you decide.

    python3 tidy.py            # run inside files/

It answers four questions the folder cannot answer by looking at it:

  1. Which svg_*.txt does a build script actually ask for, and which does no build
     script mention? An orphan figure is either a leftover or a rename that was
     half done.
  2. Does any two chapters ask for the SAME figure filename? Chapter 15's Black
     Death and chapter 27's Copenhagen plague both asked for svg_plague.txt, in a
     flat namespace shared by all 43 chapters, and nothing checked.
  3. Which bodies do the build scripts need, and which are on disk? Parts A-E have
     no retained bodies; knowing which is deliberate and which is missing matters
     before anyone tries a rebuild.
  4. Which files are near-duplicates of each other — *_patched.py, *_original.py,
     *.bak, *~ — where two generations of one file sit side by side. Three of this
     project's worst days came from editing the wrong generation.
"""
import hashlib
import os
import re
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
BUILDS = ['build_parts_abc.py', 'build_part_d.py', 'build_part_e.py',
          'build_part_f.py', 'build_part_g.py', 'build_part_h.py', 'build_all.py']


def read(p):
    try:
        return open(os.path.join(HERE, p), encoding='utf-8', errors='replace').read()
    except IOError:
        return ''


def digest(p):
    try:
        return hashlib.sha256(open(os.path.join(HERE, p), 'rb').read()).hexdigest()[:12]
    except IOError:
        return None


def main():
    files = sorted(f for f in os.listdir(HERE) if os.path.isfile(os.path.join(HERE, f)))
    print("files/  %d files\n" % len(files))

    # ---------------------------------------------------------- what wants what
    wanted_svg = defaultdict(list)      # filename -> [(build script, chapter)]
    wanted_body = {}                    # filename -> build script
    for b in BUILDS:
        src = read(b)
        if not src:
            continue
        for m in re.finditer(r'^\s*(\d+):\s*dict\(', src, re.M):
            pass
        # chapter blocks are "NN: dict(...)"; take each svgs= and body= with the
        # chapter number that precedes it
        for cm in re.finditer(r'^\s*(\d+):\s*dict\((.*?)(?=^\s*\d+:\s*dict\(|\n\}\s*$)',
                              src, re.M | re.S):
            ch, blk = cm.group(1), cm.group(2)
            for sm in re.finditer(r"'(svg_[a-z0-9_]+\.txt)'", blk):
                wanted_svg[sm.group(1)].append((b, ch))
            bm = re.search(r"body='([^']+)'", blk)
            if bm:
                wanted_body[bm.group(1)] = (b, ch)

    # ---------------------------------------------------------- what makes what
    made_by = {}
    for f in files:
        if not re.match(r'(figs?_[0-9]+[a-z]?|fig_[a-z]+|map_[0-9]+)\.py$', f):
            continue
        # Two spellings in the wild: figs_27.py writes ("svg_plague_1711.txt", fn)
        # and figs_18.py writes ("svg_fealty", fn) then open(name + ".txt").
        for m in re.finditer(r'''["'](svg_[a-z0-9_]+?)(\.txt)?["']''', read(f)):
            made_by[m.group(1) + '.txt'] = f

    on_disk = {f for f in files if f.startswith('svg_') and f.endswith('.txt')}

    # ---------------------------------------------------------- findings
    print("=" * 74)
    print("1. FIGURE FILENAME COLLISIONS — two chapters asking for one file")
    hit = False
    for name, users in sorted(wanted_svg.items()):
        chapters = sorted({c for _, c in users})
        if len(chapters) > 1:
            hit = True
            print("   !! %-26s wanted by chapters %s" % (name, ', '.join(chapters)))
            print("      whichever script ran last owns the file on disk")
    if not hit:
        print("   none")

    print()
    print("2. ORPHAN FIGURES — on disk, no build script asks for them")
    orphans = sorted(on_disk - set(wanted_svg))
    for f in orphans:
        who = made_by.get(f)
        print("   %-30s %s" % (f, ('generated by ' + who) if who
                               else 'no generator here either'))
    if not orphans:
        print("   none")

    print()
    print("3. MISSING FIGURES — a build script wants them, they are not here")
    missing = sorted(set(wanted_svg) - on_disk)
    for f in missing:
        who = made_by.get(f)
        users = ', '.join('%s ch%s' % (b.replace('build_part_', '').replace('.py', ''), c)
                          for b, c in wanted_svg[f])
        print("   %-30s wanted by %-22s %s"
              % (f, users, ('run ' + who) if who else 'NO GENERATOR — cannot be remade'))
    if not missing:
        print("   none")

    print()
    print("4. BODIES — what the build scripts need")
    for name, (b, ch) in sorted(wanted_body.items(), key=lambda x: int(x[1][1])):
        here = os.path.exists(os.path.join(HERE, name))
        alt = ('c' + name[1:]) if name[0] == 'e' else ('e' + name[1:])
        alt_here = os.path.exists(os.path.join(HERE, alt))
        state = 'present' if here else ('present as ' + alt if alt_here else 'MISSING')
        print("   ch%-3s %-20s %s" % (ch, name, state))

    print()
    print("5. TWO GENERATIONS OF ONE FILE — check before deleting either")
    seen = defaultdict(list)
    for f in files:
        base = re.sub(r'(_patched|_original|_old|_new|_fixed|\.bak|~)(?=\.|$)', '', f)
        base = base.replace('.bak', '').rstrip('~')
        seen[base].append(f)
    pairs = False
    for base, group in sorted(seen.items()):
        if len(group) > 1:
            pairs = True
            print("   %s" % base)
            for g in sorted(group):
                d = digest(g)
                sz = os.path.getsize(os.path.join(HERE, g))
                print("      %-34s %7d bytes  sha %s" % (g, sz, d))
            if len({digest(g) for g in group}) == 1:
                print("      -> identical content; keep one")
            else:
                print("      -> DIFFERENT content; diff them before removing either")
    # THE SAME NAME IN TWO DIRECTORIES, which the loop above cannot see because it
    # only ever looks inside files/. Found in Sept 2026: a stale
    # danish-history-index.html sat in files/ alongside the real one at the root,
    # and it was not merely old - it had been generated in a folder holding no
    # chapter pages, so it announced "0 pages written" and marked all 43 chapters
    # unwritten. It was committed in that state. index_generator.py writes to the
    # parent by default; anything of the same name left in files/ is a shadow.
    parent = os.path.dirname(HERE)
    for f in sorted(files):
        # Dotfiles are the operating system's business, not the project's.
        # .DS_Store exists in every directory on a Mac and differs in every one;
        # reporting it as two generations of one file is noise, and a check that
        # cries wolf is a check people stop reading.
        if f.startswith('.'):
            continue
        twin = os.path.join(parent, f)
        if not os.path.exists(twin):
            continue
        pairs = True
        here_b = open(os.path.join(HERE, f), 'rb').read()
        there_b = open(twin, 'rb').read()
        print("   %s exists in BOTH files/ and the chapter folder" % f)
        print("      files/%-28s %7d bytes" % (f, len(here_b)))
        print("      ../%-31s %7d bytes" % (f, len(there_b)))
        if here_b == there_b:
            print("      -> identical; the copy in files/ is redundant")
        else:
            print("      -> DIFFERENT. The chapter folder holds the one the pages link to.")

    if not pairs:
        print("   none")

    print()
    print("6. UNCLASSIFIED — nothing above accounted for these")
    known = set(BUILDS) | set(wanted_body) | on_disk | set(made_by.values())
    known |= {'style.css', 'rail.js', 'pagecount.py', 'mkbody.py', 'debuild.py',
              'linkindex.py', 'index_generator.py', 'bookstats.py', 'mapspine.py',
              'mapkit.py', 'mapfixture.py', 'seamcheck.py', 'tidy.py'}
    known |= {f for f in files if f.startswith('c') and f.endswith('_body.html')}
    known |= {f for f in files if f.startswith('e') and f.endswith('_body.html')}
    rest = sorted(set(files) - known)
    for f in rest:
        print("   %-40s %8d bytes" % (f, os.path.getsize(os.path.join(HERE, f))))
    if not rest:
        print("   none")

    print()
    print("=" * 74)
    print("Nothing was deleted. Read findings 1 and 5 before removing anything:")
    print("a collision means the file on disk may belong to the other chapter, and")
    print("two generations of one file is how this project has lost work before.")
    return 0


if __name__ == '__main__':
    sys.exit(main())
